coverage:
  range: "0...50"
  status:
    patch:
      default:
        target: 66%
    project:
      default:
        target: 70%
        threshold: 30%
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/d7580de27621b87e99da"
        threshold: 1%
