// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProviderInfo struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderInfo) Reset()         { *m = ProviderInfo{} }
func (m *ProviderInfo) String() string { return proto.CompactTextString(m) }
func (*ProviderInfo) ProtoMessage()    {}
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ProviderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderInfo.Unmarshal(m, b)
}
func (m *ProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderInfo.Marshal(b, m, deterministic)
}
func (m *ProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderInfo.Merge(m, src)
}
func (m *ProviderInfo) XXX_Size() int {
	return xxx_messageInfo_ProviderInfo.Size(m)
}
func (m *ProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderInfo proto.InternalMessageInfo

func (m *ProviderInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ProviderInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ProviderInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type JoinResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResult) Reset()         { *m = JoinResult{} }
func (m *JoinResult) String() string { return proto.CompactTextString(m) }
func (*JoinResult) ProtoMessage()    {}
func (*JoinResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *JoinResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResult.Unmarshal(m, b)
}
func (m *JoinResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResult.Marshal(b, m, deterministic)
}
func (m *JoinResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResult.Merge(m, src)
}
func (m *JoinResult) XXX_Size() int {
	return xxx_messageInfo_JoinResult.Size(m)
}
func (m *JoinResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResult.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResult proto.InternalMessageInfo

func (m *JoinResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*ProviderInfo)(nil), "proto.ProviderInfo")
	proto.RegisterType((*JoinResult)(nil), "proto.JoinResult")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x3f, 0x4b, 0xc7, 0x30,
	0x10, 0x86, 0x7f, 0xad, 0x5a, 0xea, 0xa9, 0x05, 0x4f, 0x90, 0xe2, 0x54, 0x82, 0x83, 0x53, 0x87,
	0xba, 0x89, 0xab, 0x5a, 0x1d, 0xa4, 0x44, 0xbf, 0x40, 0xff, 0x9c, 0x12, 0xb0, 0x49, 0x48, 0xd2,
	0x7e, 0x7e, 0xf1, 0x5a, 0xb0, 0x43, 0xa7, 0xbc, 0x79, 0x42, 0x9e, 0x7b, 0x0f, 0x2e, 0x46, 0xf2,
	0xbe, 0xfd, 0xa6, 0xd2, 0x3a, 0x13, 0x0c, 0x9e, 0xf0, 0x21, 0x3e, 0xe1, 0xbc, 0x71, 0x66, 0x56,
	0x03, 0xb9, 0x57, 0xfd, 0x65, 0xb0, 0x80, 0x33, 0x4f, 0x6e, 0x56, 0x3d, 0xbd, 0xb7, 0x23, 0xe5,
	0x51, 0x11, 0xdd, 0x9d, 0xca, 0x2d, 0xc2, 0x0c, 0x62, 0x65, 0xf3, 0x98, 0x1f, 0x62, 0x65, 0x11,
	0xe1, 0xd8, 0x1a, 0x17, 0xf2, 0x23, 0x26, 0x9c, 0xc5, 0x2d, 0xc0, 0x9b, 0x51, 0x5a, 0x92, 0x9f,
	0x7e, 0x02, 0x5e, 0x43, 0xe2, 0x38, 0xb1, 0x2e, 0x95, 0xeb, 0xad, 0x7a, 0x86, 0x54, 0x52, 0x4f,
	0x6a, 0x26, 0x87, 0x0f, 0x90, 0xfd, 0xfd, 0xf8, 0x58, 0x06, 0xd5, 0x53, 0x87, 0x57, 0x4b, 0xd1,
	0x72, 0x5b, 0xef, 0xe6, 0x72, 0x85, 0xff, 0x76, 0x71, 0xa8, 0x6a, 0x48, 0x9f, 0xf4, 0xd0, 0x18,
	0xa5, 0x03, 0x3e, 0x42, 0xf6, 0x42, 0x61, 0xd5, 0xf0, 0x46, 0xbb, 0x9e, 0x3d, 0x28, 0x0e, 0x5d,
	0xc2, 0xf4, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x56, 0x4b, 0xb3, 0x3a, 0x2c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReceiverClient is the client API for Receiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReceiverClient interface {
	JoinServiceHub(ctx context.Context, in *ProviderInfo, opts ...grpc.CallOption) (*JoinResult, error)
}

type receiverClient struct {
	cc *grpc.ClientConn
}

func NewReceiverClient(cc *grpc.ClientConn) ReceiverClient {
	return &receiverClient{cc}
}

func (c *receiverClient) JoinServiceHub(ctx context.Context, in *ProviderInfo, opts ...grpc.CallOption) (*JoinResult, error) {
	out := new(JoinResult)
	err := c.cc.Invoke(ctx, "/proto.Receiver/JoinServiceHub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiverServer is the server API for Receiver service.
type ReceiverServer interface {
	JoinServiceHub(context.Context, *ProviderInfo) (*JoinResult, error)
}

// UnimplementedReceiverServer can be embedded to have forward compatible implementations.
type UnimplementedReceiverServer struct {
}

func (*UnimplementedReceiverServer) JoinServiceHub(ctx context.Context, req *ProviderInfo) (*JoinResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinServiceHub not implemented")
}

func RegisterReceiverServer(s *grpc.Server, srv ReceiverServer) {
	s.RegisterService(&_Receiver_serviceDesc, srv)
}

func _Receiver_JoinServiceHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverServer).JoinServiceHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Receiver/JoinServiceHub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverServer).JoinServiceHub(ctx, req.(*ProviderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Receiver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Receiver",
	HandlerType: (*ReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinServiceHub",
			Handler:    _Receiver_JoinServiceHub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// EndPointClient is the client API for EndPoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndPointClient interface {
	GetServiceInfo(ctx context.Context, in *ProviderInfo, opts ...grpc.CallOption) (*ProviderInfo, error)
}

type endPointClient struct {
	cc *grpc.ClientConn
}

func NewEndPointClient(cc *grpc.ClientConn) EndPointClient {
	return &endPointClient{cc}
}

func (c *endPointClient) GetServiceInfo(ctx context.Context, in *ProviderInfo, opts ...grpc.CallOption) (*ProviderInfo, error) {
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, "/proto.EndPoint/GetServiceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndPointServer is the server API for EndPoint service.
type EndPointServer interface {
	GetServiceInfo(context.Context, *ProviderInfo) (*ProviderInfo, error)
}

// UnimplementedEndPointServer can be embedded to have forward compatible implementations.
type UnimplementedEndPointServer struct {
}

func (*UnimplementedEndPointServer) GetServiceInfo(ctx context.Context, req *ProviderInfo) (*ProviderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInfo not implemented")
}

func RegisterEndPointServer(s *grpc.Server, srv EndPointServer) {
	s.RegisterService(&_EndPoint_serviceDesc, srv)
}

func _EndPoint_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndPointServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EndPoint/GetServiceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndPointServer).GetServiceInfo(ctx, req.(*ProviderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _EndPoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EndPoint",
	HandlerType: (*EndPointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _EndPoint_GetServiceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
